package sharedModel;

import java.time.LocalDate;
import java.util.LinkedHashSet;

import server.serverModel.Orderline;

/**
 * Exercise 1 Code
 * 
 * @author Nathan Jack
 * @version 1.0
 * @since Oct 9th, 2020
 * 
 *        Sources: Code requirements from assignment
 * 
 *        Description: Order object generated by user. Hold item information for
 *        order and prints PO to console.
 */
public class Order {

	private LinkedHashSet<OrderLine> OrderLines = new LinkedHashSet<OrderLine>();
	private int orderID;
	private LocalDate date;

	/**
	 * Constructor
	 * 
	 * @param item     Item object of tool to be ordered
	 * @param supplier supplier name from tool
	 * @param orderID  unique 5 digit hash generated by shopapp at time of order.
	 */
	public Order(int orderID) {
		this.setDate();
		this.setOrderID(orderID);
	}

	public int getOrderID() {
		return orderID;
	}

	public void setOrderID(int orderID) {
		this.orderID = orderID;
	}

	public LocalDate getDate() {
		return date;
	}

	/**
	 * Set date to todays date.
	 */
	public void setDate() {
		LocalDate now = LocalDate.now();
		this.date = now;

	}

	/**
	 * Generates orderline string based on Order member variables
	 */
	public String addOrderLine(int itemId, int qty) {
		OrderLine temp = new OrderLine(itemId, qty);		
		return this.orderLineSqlInsert(temp);
	}

	public String orderLineSqlInsert(OrderLine temp) {
		return temp.getItemId() + ", " + this.getOrderID() + ", " + temp.getOrderQty();
	}
	
	public String orderSqlInsert() {
		return this.getOrderID() + ", " + this.getDate();
	}
	
	public void setOrderLines(LinkedHashSet<OrderLine> orderlines) {
		this.OrderLines = orderlines;
	}

}
