package sharedModel;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.LinkedHashSet;

/**
 * Order class to store daily order information.
 * 
 * @author NJack & JJoorisity
 * @version 1.0
 * @since 2020-11-26
 */
public class Order implements PrintTableConstants, Serializable {

	private static final long serialVersionUID = 2L;
	private LinkedHashSet<OrderLine> OrderLines = new LinkedHashSet<OrderLine>();
	private int orderID;
	private LocalDate date;

	/**
	 * Constructor
	 * @param orderID  unique 5 digit hash generated by shopapp at time of order.
	 */
	public Order(int orderID) {
		this.setDate();
		this.setOrderID(orderID);
	}

	/**
	 * @return (int) retrieve order ID.
	 */
	public int getOrderID() {
		return orderID;
	}

	/**
	 * Set the order ID.
	 * @param orderID (int) new order ID.
	 */
	public void setOrderID(int orderID) {
		this.orderID = orderID;
	}

	/**
	 * @return (LocalDate) the date of the order.
	 */
	public LocalDate getDate() {
		return date;
	}

	/**
	 * Set order date to todays date.
	 */
	public void setDate() {
		LocalDate now = LocalDate.now();
		this.date = now;

	}

	/**
	 * Add the order lines that belong to this order.
	 * @param orderlines (LinkedHashSet<OrderLine>) list of order lines to be added.
	 */
	public void setOrderLines(LinkedHashSet<OrderLine> orderlines) {
		this.OrderLines = orderlines;
	}

	/**
	 * @return (LinkedHashSet<OrderLine>) list of order lines in order.
	 */
	public LinkedHashSet<OrderLine> getOrderLines() {
		return this.OrderLines;
	}

	/**
	 * Adds a single custom OrderLine to this Order.
	 * @param itemId (integer) ItemId of tool to be ordered.
	 * @param qty (integer) qty of item to be ordered.
	 * @param supplierName (String) name of the supplier on order line.
	 */
	public void addOrderLine(int itemId, int qty,String supplierName) {
		this.OrderLines.add(new OrderLine(itemId, qty,supplierName));
	}
	
	/**
	 * Print format of order to text file.
	 */
	@Override
	public String toString() {
		String HeaderFormat = TABLEBREAK;
		HeaderFormat += "| OrderId: %-10d | Order Date: %-18s |%n";
		HeaderFormat += TABLEBREAK;
		String res = String.format(HeaderFormat, this.getOrderID(), this.getDate(), "", "");
		
		return res;
	}

}
